name: Docker Image

on:
  push:
    branches:
      - v*

jobs:
  DockerImage:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Docker Login
        uses: docker/login-action@v3.3.0
        with:
          username: ${{secrets.DOCKER_USER}}
          password: ${{secrets.DOCKER_PASS}}
      - name: Docker Build and Push
        uses: docker/build-push-action@v6.13.0
        with:
          context: ./Code
          file: ./Code/Dockerfile
          push: true
          tags: |
            rodrigobellizzieri/bitbucket-automation:latest
            rodrigobellizzieri/bitbucket-automation:${{ github.ref_name }}
            
